import '../styles/globals.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
  <Head>      
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
      <title>Weather App</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

  <Component {...pageProps} />
  </>
  )
}

export default MyApp
